version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: /start.sh
    volumes:
      - ./src:/app
    ports:
      - 80:8000
    env_file:
      - src/.env
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    env_file:
      - src/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


