version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app
    ports:
      - 80:8000
    environment:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - ./.env
